enum ModelEvents {
  VALUE_CHANGED = 'VALUE_CHANGED',
  STATE_CHANGED = 'STATE_CHANGED',
}

enum ViewEvents {
  VALUE_CHANGED = 'VALUE_CHANGED',
  VALUE_FROM_CHANGED = 'VALUE_FROM_CHANGED',
  VALUE_TO_CHANGED = 'VALUE_TO_CHANGED',
}

enum KnobEvents {
  VALUE_TO = 'VALUE_TO',
  VALUE_FROM = 'VALUE_FROM',
  KNOB_VALUE_TO_CHANGED = 'KNOB_VALUE_TO_CHANGED',
  KNOB_VALUE_FROM_CHANGED = 'KNOB_VALUE_FROM_CHANGED',
}

enum ScaleEvents {
  SCALE_VALUE_CHANGED = 'SCALE_VALUE_CHANGED',
}

enum LabelsEvents {
  LABELS_VALUE_CHANGED = 'LABELS_VALUE_CHANGED',
}

export {
  ModelEvents,
  ViewEvents,
  KnobEvents,
  ScaleEvents,
  LabelsEvents,
};